name: Run AuditLog.Tests
on:
  push:
    branches: ["main"] # 當 main 分支有 push 時觸發
    paths: 
      - 'AuditLog/**'  # 只有當 AuditLog 資料夾內的檔案有變動才執行 (可選)
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: download source code
        uses: actions/checkout@v4 # 把你的程式碼下載到虛擬機裡
  
      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Run Tests
        
        working-directory: ./AuditLog.Tests
        run: dotnet test

